# Dasar-Dasar Modul Numpy

![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

Numpy (*Numerical Python*) merupakan paket atau modul yang diperlukan dalam komputasi saintifik berperforma tinggi dan analisis data. Numpy merupakan sebuah dasar dalam penyusunan modul berlevel tinggi yang ada di python. Pada tutorial kali ini kita akan belajar:

1. Numpy ndarray
2. Fungsi matematika universal untuk array
3. Pemrosesan data menggunakan array

Untuk menginstall numpy, jalankan perintah berikut:

In [ ]:
!pip3 install numpy

Untuk mengaktifkan modul terinstall, jalankan perintah berikut:

In [ ]:
import numpy as np

## 1 Numpy ndarray

Salah satu fitur kunci dari numpy adalah *N-dimensional array object* atau `ndarray`, dimana ia merupakan kontainer yang cepat dan fleksbel untuk menangani dataset besar yang ada di python. Arrray memungkinkan kita untuk melakukan operasi matematika pada seluruh blok data menggunakan sintaks operasi yang mirip atau setara antar elemen skalar.

Sebuah `ndarray` merupakan kontainer multidimensi umum untuk data yang homogen yang berarti jenis data dalam kontainer haruslah sejenis. Setiap array memiliki bentuk (`shape`), sebuah tuple yang mengidentifikasikan dimensi array dan `dtype` yang mendeksripsikan jenis data sebuah array.

### 1.1 Membuat ndarray

Cara termudah untuk membuat sebuah array adalah dengan menggunakan fungsi `array`. Fungsi ini menerima sejumlah *sequence-like object* dan menghasilkan array yang berisikan data yang telah diinputkan sebelumnya.

In [ ]:
# simple array
data1 = [1, 1, 4, 5, 6, 8]
arr1 = np.array(data1)
arr1

array([1, 1, 4, 5, 6, 8])

Untuk mengecek dimensi array, gunakan method `ndim` atau `shape`.

In [ ]:
arr1.ndim

1

In [ ]:
arr1.shape

(6,)

Untuk cek jenis data yang ada di dalam array, gunakan method `dtype`.

In [ ]:
arr1.dtype

dtype('int64')

Selain fungsi `array`, terdapat fungsi lain yang dapat digunakana  untuk membentuk array. Sebagai contoh `zeros` dan `ones`, meruapak sebuah fungsi untuk membentuk array dengan elemen berupa angka nol dan satu. Argumen tambahan yang diberikan berupa dimensi dari array yang ingin dibentuk.

In [ ]:
# array 2 baris dan 3 kolom
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# array dengan 10 elemen
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Fungsi-fungsi lain yang dapat digunakan untuk membuat sebuah array dirangkum dalam tabel berikut:

| Fungsi        | Deksripsi                                                |
|:--------------|:---------------------------------------------------------|
| array         | mengkonversi data input (list, tuple, array, atau tipe deret angka lainnya) menjadi ndarray |
| asarray       | mengkonversi data input menjadi array tanpa mengcopy data yang dihasilkan jika data input adalah array|
| arrange       | seperti fungsi `arrange` yang telah ada di python, namun menghasilkan array dan bukan list |
| ones, ones_like | memproduksi sebuah array dnegan seluruh elemen berupa angka 1 dengan `shape` dan `dtype` yang diberikan. |
|               | `ones_like` mengambil input array lainnya dan mengkonversinya menjadi array dengan elemen 1 tanpa mengubah dimensi dan jenis data di dalamnya|
| zeros, zeros_like | seperti fungsi `ones` tapi menghasilkan array dengan nilai elemen 0 |
| empty, empty_like | membuat array dengan mengalokasikan memori baru, tapi tidak mengisi array yang terbentuk dengan angka nol atau satu |
|eye, identity | membuat sebuah N x N matriks identitas persegi    |

### 1.2 Jenis Data ndarray

Jenis data merupakan sebuah objek spesial yang berisikan informasi yang diperlukan oleh ndarray untuk menginterpretasikan sebuah *chunk memory* sebagai bagian dari  jenis data tertentu.

In [ ]:
arr2 = np.array([1,2,3], dtype=np.float64)
arr2.dtype

dtype('float64')

Dtypes adalah bagian dari apa yang membuat NumPy begitu kuat dan fleksibel. Dalam kebanyakan kasus, numpy memetakan langsung ke representasi mesin yang mendasari, yang membuatnya mudah untuk membaca dan menulis aliran data biner disk dan juga untuk menyambung ke kode yang ditulis dalam bahasa tingkat rendah seperti C atau Fortran. Dtypes numerik diberi nama dengan cara yang sama: nama tipe, seperti float atau int, diikuti dengan angka yang menunjukkan jumlah bit per elemen. Nilai floating point presisi ganda standar (apa yang digunakan di balik objek float Python) membutuhkan 8 byte atau 64 bit. Jadi, tipe ini dikenal di NumPy sebagai float64. Untuk melihat daftar lengkap dari jenis data yang didukung oleh numpy, perhatikan tabel berikut:



| Tipe           | Kode Tipe       | Deskripsi                                 |
|:---------------|:----------------|:------------------------------------------|
| int8, uint8    | i1, u1          | Signed dan unsigned 8-bit (1 byte) integer types|
| int16, uint16  | i2, u2          | Signed dan unsigned 16-bit integer types  |
| int32, uint32  | i4, u4          | Signed dan unsigned 32-bit integer types  |
| int64, uint64  | i8, u8          | Signed dan unsigned 32-bit integer types  |
| float16        | f2              | Half-precision floating point             |
| float32        | f4 atau f       | Standard single-precision floating point  Kompatibel dengan C float                 |
| float64, float128 | f8 atau d    | Standard double-precision floating point. Kompatibel dengan C double dan Python float object |
| float128      | f16 atau g       | Extended-precision floating point         |
| complex64, complex128, complex256 | c8, c16, c32 | Bilangan kompleks yang direpresentasikan oleh dua 32, 64, atau 128 float|
| bool          | ?                 | Nilai boolean                            |
| object        | 0                 | Python object type                       |
| string_       | S                 | String                                   |
| unicode_      | U                 | Unicode                                  |


Dengan menggunakan panduan tabel tersebut, kita dapat melakukan modifikasi jenis data pada array yang telah kita buat.

In [ ]:
arr2 = arr2.astype(np.int64)
arr2.dtype

dtype('int64')

### 1.3 Operasi antara Array dan Scalar

Array merupakan sebuah objek yang penting, sebab array memungkinkan kita melakukan operasi pada data tanpa menuliskan `for` loop. Operasi ini biasanya dinamai operasi tervektorisasi. Setiap operasi aritmatik antara array dengan ukuran elemen yang sama akan dilakukan secara *elementwise*. 

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

# hitung invers masing-masing elemen
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr - 1/arr

array([[0.        , 1.5       , 2.66666667],
       [3.75      , 4.8       , 5.83333333]])

### 1.4 Subset Array

Proses pengindeksan pada array secara prinsip akan berbeda berdasarkan dimensi yang dimiliki array tersebut.

In [ ]:
# subset array satu dimensi
arr1[:3]

array([1, 1, 4])

In [ ]:
# subset array 2 dimensi
arr[1,[0,2]]

array([4., 6.])

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:

# subset array 3 dimensi
arr3d[1,:][1,:]

array([10, 11, 12])

## 2 Fungsi Matematika Universal pada Array

Fungsi universal (*ufunc*) merupakan sebuah fungsi yang melakukan operasi secara *elementwise* terhadap ndarray. Kita dapat membayangkannya sebagai sebuah fungsi tervektorisasi yang mengambil sebuah input berupa satu atau beberapa nilai skalar dan menghasilkan satu atau beberapa nilai skalar.

Terdapat dua macam fungsi universal yang akan umum digunakan, yaitu:
1. **unary** : menerima input sebuah array
2. **binary** : menerima input dua buah array 

Berikut adalah ringkasan fungsi universal unary yang bisa digunakan:

| Fungsi              | Deskripsi                                   |
|:--------------------|:--------------------------------------------|
| abs, fabs           | menghitung nilai absolut array numerik. Gunakan fabs sebagai alternatif komputasi yang lebih cepat untuk *non-complex-valued data*|
| sqrt                | menghitung nilai akar kuadrat bilangan. Setara dengan array ** 0,5  |
| square              | menghitung kuadrat bilangan. Setara dengan array ** 2 |
| exp                 | menghitung nilai eksponen dari $e^x$ |
| log, log10, log2, log1p | menghitung nilai log natural (basis e), log basis 10, log basis 2 dan log basis (1+x) |
| sign                | menghitung *sign* masing-masing elemen: 1 (positif), 0 (nol), dan -1 (negatif) |
| ceil                | melakukan pembulatan ke atas                |
| floor               | melakukan pembulatan ke bawah               |
| rint                | membulatkan nilai ke integer terdekat dengan tetap mempertahankan tipe data array |
| modf                |Ubah bagian pecahan dan integral dari array sebagai array terpisah |
| isnan               | menghasilkan nilai boolean yang mengidentifikasikan apakah elemen array merupakan missing value atau bukan |
| isfinite, isinf     | menghasilkan nilai boolean yang mengidentifikasikan apakah elemen array merupakan bilangan finit atau bukan, dan sebaliknya |
| cos, cosh, sin, sinh, tan, tanh | fungsi trigonometri biasa dan hiperbolik |
| arccos, arccosh, arcsin, arcsinh, arctan, arctanh | fungsi inverse trigonometri |
| logical_not         | menghitung nilai sebenarnya dari bukan (*not*) x |  

In [ ]:
# sampel array
arr1 = np.arange(10)
arr2 = arr1 * 3

In [ ]:
# akar kuadrat
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
# sign
np.sign(arr2)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Berikut adalah ringkasan dari fungsi binary:

| Fungsi          | Deskripsi                                                  |
|:----------------|:-----------------------------------------------------------|
| add             | menjumlahkan elemen array                                  |
| substract       | mengurangkan nilai elemen array pertama dengan array kedua |
| multiply        | operasi perkalian elemen array                             |
| divide, floor_divide | operasi pembagian                                     |
| power           | operasi pemangkatan array pertama terhadap array kedua     |
| maximum, fmax   | membandingkan dan mencari nilai maksimum antar dua elemen  |
| minimum, fmin   | membandingkan dan mencari nilai minimum antar dua elemen   |
| mod             | *element-wise modulus*                                     |
| copysign        | melakukan copy sign nilai argumen kedua ke argumen pertama |
| greater, greater_equal, less, less_equal, equal, not_equal | melakukan perbandingan  elemen array pertama dengan kedua |
| logical_and, logical_or, logical_xor | melakukan operasi logik               |

In [ ]:
np.maximum(arr1,arr2)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.divide(arr2, arr1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

## 3 Pemrosesan Data Menggunakan Array

Menggunakan array NumPy memungkinkan kita untuk mengekspresikan berbagai jenis tugas pemrosesan data sebagai ekspresi array yang ringkas yang mungkin memerlukan loop penulisan. Praktik mengganti loop eksplisit dengan ekspresi array ini biasanya disebut sebagai vektorisasi. Secara umum, operasi array vektorisasi sering kali satu atau dua (atau lebih) lipat lebih cepat daripada padanan Python murni mereka, dengan dampak terbesar dalam jenis perhitungan numerik.

### 3.1 Mengekspresikan Logika Bersyarat sebagai Operasi Array

Fungsi `where` merupakan bentuk tervektorisasi dari ekspresi `x if condition else y`. Misalkan kita memiliki array dengan elemen boolean dan dua buah array numerik:

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

Misalkan kita ingin mengambil nilai dari `xarr` setiap nilai dalam `cond` adalah `True` dan sebaliknya ambil nilai pada `yarr`. Penulisan loop untuk kondisi tersebut adalah sebagai berikut:

In [ ]:
result = [(x if c else y) 
        for x, y, c in zip(xarr, yarr, cond)]

result

[1.1, 2.2, 1.3, 1.4, 2.5]

Bentuk tervektorisasinya adalah sebagai berikut:

In [ ]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

### 3.2 Metode Matematik dan Statistik

Serangkaian fungsi matematika yang menghitung statistik tentang seluruh array atau tentang data di sepanjang sumbu dapat diakses menggunakan array method. Agregasi (sering disebut reduksi) seperti sum, mean, dan standar deviasi dapat digunakan dengan memanggil metode instance array atau menggunakan fungsi NumPy:

In [ ]:
arr = np.random.randn(5, 4)
arr.mean()

0.22830916575101073

Contoh lainnya adalah sebagai berikut:

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [ ]:
arr.mean(axis = 1)

array([1., 4., 7.])

Fungsi dasar metode statistik yang dapat digunakan pada array dirangkum pada tabel berikut:

| Method        | Deskripsi                               |
|:--------------|:----------------------------------------|
| sum           | jumlah seluruh elemen array atau sepanjang axis |
| mean          | mean aritmatik array                    |
| std, var      | simpangan dan varians                   |
| min, max      | nilai minimum dan maksimum              |
| argmin, agrmax| indeks minimum dan maksimum elemen      |
| cumsum        | jumlah kumulatif elemen                 |
| cumprod       | produk kumulatif elemen                 |

## 4 Referensi

Jika pembaca ingin mempelajari modul Numpy lebih lanjut, gunakan referensi pada tautan berikut:

1. [Tutorial Numpy](https://numpy.org/learn/)
2. [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)